#!/bin/bash
sudo yum install java-1.8.0-openjdk-devel wget -y
cd /opt
sudo wget http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
tar -xvzf apache-tomcat-8.5.54.tar.gz
chmod +x /opt/apache-tomcat-8.5.54/bin/startup.sh
chmod +x /opt/apache-tomcat-8.5.54/bin/shutdown.sh
sed -i '19d' /opt/apache-tomcat-8.5.54/webapps/manager/META-INF/context.xml
sed -i '20d' /opt/apache-tomcat-8.5.54/webapps/manager/META-INF/context.xml
sed -i '44d' /opt/apache-tomcat-8.5.54/conf/tomcat-users.xml
cat << EOF >> /opt/apache-tomcat-8.5.54/conf/tomcat-users.xml
        <role rolename="manager-gui"/>
        <role rolename="manager-script"/>
        <role rolename="manager-jmx"/>
        <role rolename="manager-status"/>
        <user username="admin" password="admin" roles="manager-gui, manager-script, manager-jmx, manager-status"/>
        <user username="deployer" password="deployer" roles="manager-script"/>
        <user username="tomcat" password="s3cret" roles="manager-gui"/>
</tomcat-users>
EOF
cd /opt/apache-tomcat-8.5.54/bin/
sh startup.sh


